-- SCHEMA CREATION
CREATE SCHEMA PlayerSchema;
CREATE SCHEMA AccountSchema;
CREATE SCHEMA GameSchema;
CREATE SCHEMA TransactionSchema;
CREATE SCHEMA EmployeeSchema;
CREATE SCHEMA ESportsSchema;

-- ROLE CREATION
CREATE ROLE PlayerRole;
CREATE ROLE EmployeeRole;
CREATE ROLE ManagerRole;

-- GRANT SCHEMA PERMISSIONS
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA PlayerSchema TO PlayerRole;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA AccountSchema TO PlayerRole;
GRANT SELECT ON ALL TABLES IN SCHEMA GameSchema TO PlayerRole;
GRANT SELECT ON ALL TABLES IN SCHEMA ESportsSchema TO PlayerRole;

GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA EmployeeSchema TO EmployeeRole;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA PlayerSchema TO EmployeeRole;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA AccountSchema TO EmployeeRole;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA TransactionSchema TO EmployeeRole;
GRANT SELECT, INSERT, UPDATE ON ALL TABLES IN SCHEMA ESportsSchema TO EmployeeRole;

GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA PlayerSchema TO ManagerRole;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA AccountSchema TO ManagerRole;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA GameSchema TO ManagerRole;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA TransactionSchema TO ManagerRole;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA EmployeeSchema TO ManagerRole;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA ESportsSchema TO ManagerRole;

-- CREATE ENUMS
CREATE TYPE Role AS ENUM('Employee', 'Manager');
CREATE TYPE ApprovalStatus AS ENUM('Pending', 'Approved', 'Rejected');
CREATE TYPE TournamentResultStatus AS ENUM('First', 'Second', 'Third', 'Discontinued');

